//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOS.Core.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Used All Of Your Withdraw Chances.
        /// </summary>
        public static string AllWithdrawUsed {
            get {
                return ResourceManager.GetString("AllWithdrawUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites With And Relation Between Them.
        /// </summary>
        public static string AndRelationPrerequisites {
            get {
                return ResourceManager.GetString("AndRelationPrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bifuraction.
        /// </summary>
        public static string Bifuraction {
            get {
                return ResourceManager.GetString("Bifuraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Enroll In An Enhancement Course.
        /// </summary>
        public static string CantEnrollEnhancementCourse {
            get {
                return ResourceManager.GetString("CantEnrollEnhancementCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Withdraw From Any Course.
        /// </summary>
        public static string CantWithdraw {
            get {
                return ResourceManager.GetString("CantWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coures Registration.
        /// </summary>
        public static string CouresRegistration {
            get {
                return ResourceManager.GetString("CouresRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Addition And Deletion.
        /// </summary>
        public static string CourseAddDelete {
            get {
                return ResourceManager.GetString("CourseAddDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Course Already Exist.
        /// </summary>
        public static string CourseAlreadyExist {
            get {
                return ResourceManager.GetString("CourseAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Course You Have Requested Sheet For Doesn&apos;t Have a {0} Marks.
        /// </summary>
        public static string CourseDoesntHaveThisMarkType {
            get {
                return ResourceManager.GetString("CourseDoesntHaveThisMarkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Enhancement.
        /// </summary>
        public static string CourseEnhancement {
            get {
                return ResourceManager.GetString("CourseEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Excuse.
        /// </summary>
        public static string CourseExcuse {
            get {
                return ResourceManager.GetString("CourseExcuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Overload.
        /// </summary>
        public static string CourseOverload {
            get {
                return ResourceManager.GetString("CourseOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Withdraw.
        /// </summary>
        public static string CourseWithdraw {
            get {
                return ResourceManager.GetString("CourseWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Does Not Exist.
        /// </summary>
        public static string DoesntExist {
            get {
                return ResourceManager.GetString("DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elective.
        /// </summary>
        public static string Elective {
            get {
                return ResourceManager.GetString("Elective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Exist.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The List Can&apos;t Be Empty.
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred While Processing Your Request.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall.
        /// </summary>
        public static string Fall {
            get {
                return ResourceManager.GetString("Fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Is Not Valid.
        /// </summary>
        public static string FileNotValid {
            get {
                return ResourceManager.GetString("FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Exam.
        /// </summary>
        public static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Level.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available For 4th Year Students Only.
        /// </summary>
        public static string For4thYearOnly {
            get {
                return ResourceManager.GetString("For4thYearOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Level.
        /// </summary>
        public static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Regular Semester&apos;s GPA Must Be &gt;= 3.0.
        /// </summary>
        public static string GpaAbove3 {
            get {
                return ResourceManager.GetString("GpaAbove3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Opening For Graduation.
        /// </summary>
        public static string GraduationCourse {
            get {
                return ResourceManager.GetString("GraduationCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Can&apos;t Be Empty.
        /// </summary>
        public static string IDCantBeEmpty {
            get {
                return ResourceManager.GetString("IDCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Data Is Invalid.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Can&apos;t Be Greater than Or Equal To End Date.
        /// </summary>
        public static string InvalidDateinterval {
            get {
                return ResourceManager.GetString("InvalidDateinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID.
        /// </summary>
        public static string InvalidID {
            get {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandetory.
        /// </summary>
        public static string Mandetory {
            get {
                return ResourceManager.GetString("Mandetory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Don&apos;t Have Any Enhancement Credit Left.
        /// </summary>
        public static string NoEnhancementCredit {
            get {
                return ResourceManager.GetString("NoEnhancementCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s No More Bifuraction For You.
        /// </summary>
        public static string NoMoreBifuraction {
            get {
                return ResourceManager.GetString("NoMoreBifuraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t Have Any Prerequisite.
        /// </summary>
        public static string NoPrerequisite {
            get {
                return ResourceManager.GetString("NoPrerequisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Is Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Only {0} Chances And You Requested For {1}.
        /// </summary>
        public static string NotEnoughWithdrawChances {
            get {
                return ResourceManager.GetString("NotEnoughWithdrawChances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Value Is : {0} New Value Is {1}.
        /// </summary>
        public static string OldToNewValue {
            get {
                return ResourceManager.GetString("OldToNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has 1 Prerequisite Only.
        /// </summary>
        public static string OnePrerequisite {
            get {
                return ResourceManager.GetString("OnePrerequisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral.
        /// </summary>
        public static string Oral {
            get {
                return ResourceManager.GetString("Oral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites With Or Relation Between Them.
        /// </summary>
        public static string OrRelationPrerequisites {
            get {
                return ResourceManager.GetString("OrRelationPrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical.
        /// </summary>
        public static string Practical {
            get {
                return ResourceManager.GetString("Practical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Admin.
        /// </summary>
        public static string ProgramAdmin {
            get {
                return ResourceManager.GetString("ProgramAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Transfer.
        /// </summary>
        public static string ProgramTransfer {
            get {
                return ResourceManager.GetString("ProgramTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored Successfully.
        /// </summary>
        public static string Restored {
            get {
                return ResourceManager.GetString("Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Level.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Level.
        /// </summary>
        public static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Requirement.
        /// </summary>
        public static string UniversityRequirement {
            get {
                return ResourceManager.GetString("UniversityRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Grades Sheet For Final Exam.
        /// </summary>
        public static string UploadFinalGradesSheets {
            get {
                return ResourceManager.GetString("UploadFinalGradesSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Grades Sheet For Year Work Exams.
        /// </summary>
        public static string UploadYearWorkGradesSheets {
            get {
                return ResourceManager.GetString("UploadYearWorkGradesSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Sheet Is For {0} While Requested Course Is For {1}.
        /// </summary>
        public static string WrongUploadedSheetFile {
            get {
                return ResourceManager.GetString("WrongUploadedSheetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Work Grades.
        /// </summary>
        public static string YearWork {
            get {
                return ResourceManager.GetString("YearWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Register To These Courses.
        /// </summary>
        public static string YouCantRegister {
            get {
                return ResourceManager.GetString("YouCantRegister", resourceCulture);
            }
        }
    }
}
